Numpy Arrays

In [1]:
my_list = [1,2,3]

In [4]:
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2) #start, stop, step

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3)) # two rows and three column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4) # I matrix square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5) #  random from 0 to 1

array([0.92838973, 0.51588405, 0.05258362, 0.63168277, 0.1499942 ])

In [22]:
np.random.rand(5,5)

array([[0.1885295 , 0.13538562, 0.97024448, 0.53313052, 0.44243754],
       [0.00315983, 0.25207018, 0.6888799 , 0.90691664, 0.8074976 ],
       [0.94546809, 0.38276117, 0.75205869, 0.53933532, 0.25163788],
       [0.92526053, 0.12847121, 0.2988773 , 0.21933287, 0.22307048],
       [0.15676148, 0.16833063, 0.93157197, 0.72630087, 0.17349828]])

In [33]:
ranarr = np.random.randint(0,50,10) #start, stop, size
ranarr

array([28, 35, 21, 27, 49, 36, 38, 45, 28, 43])

In [34]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr

array([28, 35, 21, 27, 49, 36, 38, 45, 28, 43])

In [40]:
ranarr.min()

21

In [41]:
ranarr.max()

49

In [42]:
ranarr.argmax()

4

In [43]:
ranarr.argmin()

2

In [45]:
arr =arr.reshape(5,5)
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')

Numpy Indexing and Selection

In [47]:
arr = np.arange(0,11)
arr[8]

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
slice_of_arr = arr[0:6] # don't copy , it's link
slice_of_arr[:]=99

In [52]:
arr_copy = arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[0][0]
# arr_2d[1,2] same arr_2d[1][2]

5

In [59]:
arr_2d[:2,1:] # row , column

array([[10, 15],
       [25, 30]])

In [62]:
arr = np.arange(1,11)
bool_arr= arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr] # print element true
# same arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr<3]

array([1, 2])

In [66]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])